fek

--[[files {
    'diables_x_quasar_phone.ytyp',
    'diables_x_quasar_phone_black.ydr',
    'diables_x_quasar_phone_blue.ydr',
    'diables_x_quasar_phone_gold.ydr',
    'diables_x_quasar_phone_green.ydr',
    'diables_x_quasar_phone_greenlight.ydr',
    'diables_x_quasar_phone_grey.ydr',
    'diables_x_quasar_phone_pink.ydr',
    'diables_x_quasar_phone_purple.ydr',
    'diables_x_quasar_phone_red.ydr',
    'diables_x_quasar_phone_txd.ydr',
    'diables_x_quasar_phone_white.ydr',
}

data_file 'DLC_ITYP_REQUEST' 'diables_x_quasar_phone.ytyp']]

ui_page "html/index.html"

client_scripts {
    'config/config.lua',
    'config/config_framework.lua',
    'client/functions_framework.lua',
    'client/main.lua',
    'client/uber.lua',
    'client/photo.lua',
    'client/rentel.lua',
    'client/valet.lua',
    'client/discord.lua',
    'client/room_creation.lua',
    'client/business.lua',
    'client/pincode.lua',
    'config/config_discord.lua',
    'config/config_vehicles.lua',
    'config/config_pincode.lua',
    'config/config_animations.lua',
    'config/config_rentel.lua',
    'config/config_uber.lua',
    'config/config_client.lua',
    'config/config_radio.lua',
    'config/config_calls_client.lua',
    'config/config_invoices_client.lua',
    'config/config_business.lua',
    'config/translations.lua',
}

server_scripts {
    'config/config.lua',
    'config/config_discord.lua',
    'config/config_framework.lua',
    'server/functions_framework.lua',
    'config/config_webhook.lua',    
    'server/main.lua',
    'server/discord.lua',
    'server/room_creation.lua',
    'config/translations.lua',
    'config/config_pincode.lua',
    'config/config_server.lua',
	'config/config_valet.lua',
    'config/config_rentel.lua',
    'config/config_uber.lua',
    'config/config_banking.lua',
    'config/config_calls_server.lua',
    'config/config_invoices_server.lua',
    'config/config_commands.lua',
    'config/config_business.lua',
    'server/version_check.lua',
}

files {
    'html/index.html',

    'html/js/bottomselector.js
    'html/js/emojiinarea.js',
    'html/js/group-chats.js',
    'html/js/jquery.ios.picker.js',
    'html/js/jquery.slick.js',
    'html/js/jquery.slick.min.js',
    'html/js/jquery.timeago.js',
    'html/js/lockscreen.js',
    'html/js/main.js',
    'html/js/uberDriver.js',

    'config/config_javascript.js',
    'config/config_discord.js',
    'config/translations.js',

    'html/img/black_frame.png',
    'html/img/blue_frame.png',
    'html/img/classic_frame.png',
    'html/img/gold_frame.png',
    'html/img/green_frame.png',
    'html/img/greenlight_frame.png',
    'html/img/pink_frame.png',
    'html/img/purple_frame.png',
    'html/img/red_frame.png',
    'html/img/white_frame.png',
    'html/sounds/phone_alarm.mp3',
    'html/sounds/phone_camera.mp3',
    'html/sounds/phone_keypad.mp3',
    'html/sounds/phone_lockscreen.mp3',
    'html/sounds/phone_notification.mp3',
    'html/sounds/phone_ringtone.mp3',
    'html/sounds/phone_vibration.mp3',

    'html/css/darkchat.css',
    'html/css/darkweb.css',
    'html/css/draggable.css',
    'html/css/flappy.css',
    'html/css/garage.css',
    'html/css/group-chats.css',
    'html/css/houses.css',
    'html/css/instagram.css',
    'html/css/instagram-filters.min.css',
    'html/css/jump.css',
    'html/css/kong.css',
    'html/css/mail.css',
    'html/css/ main.css',
    'html/css/meos.css',
    'html/css/messages.css',
    'html/css/music.css',
    'html/css/notes.css',
    'html/css/numberpicker.css',
    'html/css/other.css',
    'html/css/pacman.css',
    'html/css/phone.css',
    'html/css/photos.css',
    'html/css/pincode.css',
    'html/css/ping.css',
    'html/css/racing.css',
    'html/css/radio.css',
    'html/css/rentel.css',
    'html/css/settings.css',
    'html/css/slick.css',
    'html/css/society.css',
    'html/css/spotify.css',
    'html/css/state.css',
    'html/css/store.css',
    'html/css/stories.css',
    'html/css/tinder.css',
    'html/css/twitter.css',
    'html/css/uber.css',
    'html/css/uberDriver.css',
    'html/css/weather.css',
    'html/css/whatsapp.css',
    'html/css/youtube.css',
    'html/css/advert.css',
    'html/css/bank.css',
    'html/css/business.css',
    'html/css/calculator.css',
    'html/css/calendar.css',
    'html/css/clock.css',
    
    'html/fonts/CircularStd-Bold.otf',
    'html/fonts/CircularStd-Medium.otf',
    'html/fonts/ios.ttf',

    'html/img/uberDriver/*.png',
    'html/img/backgrounds/*.png',
    'html/img/apps/*.png',
	'html/img/app_details/*.png',
    'html/img/business/*.png',
    'html/img/darkweb_items/*.png',
}
